### ISSUE TITLE
(Windows) npm run devがコマンドエラーになる

### ISSUE THREAD

**Issue by rioaki777** [kght6123/techbook-template#7]
### - dev:sync / dev:sync:lock
**[Issue]**
シングルクォートをパスの一部として認識してしまいエラーが発生します。

**[proposal]**
シングルクォートの削除、またはダブルクォートに変更する事で動作確認しております。

### - pre-compiler:dev
**[Issue]**
セミコロンをコマンドの一部として認識してしまいエラーが発生します。

**[proposal]**
&や&&に変更し動作確認しております。

**Comment by kght6123** [comment]
@rioaki777 ご連絡、ありがとうございます！

ちょうど、Windowsでの動作確認をせねばと思って端末が届いたところなので、こちらでも念の為、試してみてから取り込みしようと思います🙏

ありがとうございます！
